[tool.ruff]
line-length = 120
target-version = 'py310'

[tool.ruff.lint]
select = ['E', 'Q', 'T20', 'F', 'N', 'C4', 'I', 'UP', 'A', 'SIM', 'TID', 'A']
ignore = ['T201', 'E712', 'SIM117']

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true

[tool.ruff.lint.flake8-quotes]
docstring-quotes = 'double'
inline-quotes = 'single'
multiline-quotes = 'double'
